#!/bin/bash

# ================================
# INFO: template-bash-functions.sh
# ================================


# =====================================
# VARIABLEN: template-bash-functions.sh
# =====================================
MNVAR="$HOME/my-net/env-vars"
MNFUNC="$HOME/my-net/scripts/bash/func"
MNHAND="$HOME/my-net/scripts/bash/handlers"


# ====================================
# FUNCTION: template-bash-functions.sh
# ====================================


# ====================================
case $1 in
    "$1")
        $1
        ;;
esac