#!/bin/bash

# ==============================
# INFO: template-bash-scripts.sh
# ==============================


# ===================================
# VARIABLEN: template-bash-scripts.sh
# ===================================
MNVAR="$HOME/my-net/env-vars"
MNFUNC="$HOME/my-net/scripts/bash/func"
MNHAND="$HOME/my-net/scripts/bash/handlers"


# ==================================
# FUNCTION: template-bash-scripts.sh
# ==================================


# ==================================
case $1 in
    "$1")
        $1
        ;;
esac