#!/bin/bash

# ==============================
# INFO: template-bash-scripts.sh
# ==============================


# VARIABLEN
# =========
MNVAR="$HOME/my-net/env-vars"
MNFUNC="$HOME/my-net/scripts/bash/func"
MNHAND="$HOME/my-net/scripts/bash/handlers"


# FUNCTIONS
# =========


# PROGRAM
# =======
